name: healify_me
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  firebase_auth: ^5.1.3
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.3.1
  image_picker: ^1.1.2
  firebase_storage: ^12.1.3
  zego_uikit_prebuilt_call: 4.14.3
  zego_uikit_signaling_plugin: ^2.8.2
  zego_uikit_prebuilt_live_streaming: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
