// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7QxU-OF8A3vnpAOrU9Pnt3CRa47IQhp8',
    appId: '1:110569929519:web:046295f5e15a8e9f223fda',
    messagingSenderId: '110569929519',
    projectId: 'healifyme-30323',
    authDomain: 'healifyme-30323.firebaseapp.com',
    storageBucket: 'healifyme-30323.appspot.com',
    measurementId: 'G-T8E2P5ZZWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdR80C9bm6kZTIR5GpfXLUsKYiOw4xMLc',
    appId: '1:110569929519:android:e64cf394b772ac96223fda',
    messagingSenderId: '110569929519',
    projectId: 'healifyme-30323',
    storageBucket: 'healifyme-30323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC863y53VsD4GosWu7azXykuI8ZlVS0OcE',
    appId: '1:110569929519:ios:f54b1aa7a1fa82b0223fda',
    messagingSenderId: '110569929519',
    projectId: 'healifyme-30323',
    storageBucket: 'healifyme-30323.appspot.com',
    iosBundleId: 'com.example.healifyMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC863y53VsD4GosWu7azXykuI8ZlVS0OcE',
    appId: '1:110569929519:ios:f54b1aa7a1fa82b0223fda',
    messagingSenderId: '110569929519',
    projectId: 'healifyme-30323',
    storageBucket: 'healifyme-30323.appspot.com',
    iosBundleId: 'com.example.healifyMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7QxU-OF8A3vnpAOrU9Pnt3CRa47IQhp8',
    appId: '1:110569929519:web:b7312e1bf18db482223fda',
    messagingSenderId: '110569929519',
    projectId: 'healifyme-30323',
    authDomain: 'healifyme-30323.firebaseapp.com',
    storageBucket: 'healifyme-30323.appspot.com',
    measurementId: 'G-8LG6GD29RR',
  );
}
